GestionClub/Controllers/ActiviteController.cs
using BLL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Models.Activites;
using Models.Membres;

namespace GestionClub.Controllers
{
    [Authorize]
    public class ActiviteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult listClub()
        {

            ClubService clubService = new ClubService();

            ViewBag.IdClub = clubService.ListeClub();



            return View();


        }
        public IActionResult list(int id)
        {
            ActiviteService activiteService = new ActiviteService();
            ClubService clubService = new ClubService();

            ViewBag.Clubs = clubService.ListeClub();

            if (id != 0)
            {
                ViewBag.nbrActivite = activiteService.nbrActivite();
                return View(activiteService.ActiviteParClub(id));
            }

                

            else
            {
                return View(null);
            }
        }
        public ActionResult Create()
        {
            ClubService clubService = new ClubService();

            ViewData["Titre"] = "Creation d'activites";

            ViewBag.IdClub = clubService.ListeClub();


            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ActiviteVM model)
        {


            try
            {
                ActiviteService service = new ActiviteService();
                service.Ajouter(model);
                return RedirectToAction("list","Club");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            ActiviteService activiteService = new ActiviteService();

            ViewData["Titre"] = "Supression d'une activité";
            activiteService.Supprimer(id);
            return RedirectToAction("list", "Club");
        }
        public ActionResult Edit(int id)
        {
            ActiviteService activiteService = new ActiviteService();
            ClubService club = new ClubService();

            ViewBag.IdClub = club.ListeClub();
            ViewData["Titre"] = "Modifier une activité";


            ActiviteVM act = activiteService.Trouver(id);


            return View(act);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ActiviteVM activite)
        {
            try
            {
                ClubService club = new ClubService();

                ViewBag.IdClub = club.ListeClub();
                ActiviteService service = new ActiviteService();
                service.Modifier(activite);
                return RedirectToAction("list", "Club");
            }
            catch
            {
                return View(nameof(Edit), activite);
            }
        }


    }
}

GestionClub/Controllers/ClubController.cs
using BLL;
using Microsoft.AspNetCore.Mvc;
using Models.Club;
using Models.Membres;
using DAL.Entity;
using Microsoft.AspNetCore.Authorization;

namespace GestionClub.Controllers
{
    [Authorize]
    
    public class ClubController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult list()
        {
            ClubService clubService = new ClubService();

            ViewBag.nombreClub = clubService.NbrClubs();
                return View(clubService.ListeClub());

        }
        public ActionResult Create()
        {

            ViewData["Titre"] = "Creation de Club";


            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClubVM model)
        {
            


            try
            {
                ClubService service = new ClubService();
                service.Ajouter(model);
                return RedirectToAction(nameof(list));
            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult Delete(int id)
        {
            ClubService clubService = new ClubService();

            ViewData["Titre"] = "Supression de club";
            clubService.Supprimer(id);
            return RedirectToAction(nameof(list));
        }
        
        
        public ActionResult Edit(int id)
        {
            ClubService clubService = new ClubService();

            ViewData["Titre"] = "Modifier un club";

           
            ClubVM club = clubService.Trouver(id);

            TempData["Id"] = id;
            if (club == null)
            {
                return NotFound();
            }

            return View(club);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClubVM club)
        {
            try
            {
                club.Id = (int)TempData["Id"];
                ClubService service = new ClubService();
                service.Modifier(club);
                return RedirectToAction(nameof(list));
            }
            catch
            {
                return View(nameof(Edit), club);
            }
        }




    }
}

GestionClub/Controllers/MembreController.cs
using Microsoft.AspNetCore.Mvc;
using BLL;
using Models.Membres;
using Models.Club;
using DAL.Entity;
using Microsoft.AspNetCore.Authorization;
using GestionClub.Controllers;

namespace GestionClubs.Controllers
{
    [Authorize]
    public class MembreController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult listClub()
        {
            
            ClubService clubService = new ClubService();

            ViewBag.IdClub = clubService.ListeClub();

            

                return View();

            
        }
        public IActionResult list(int id)
        {
            MembreService membreService = new MembreService();
            
            
            if(id !=0)
            {
                ViewBag.nbrMembre = membreService.nbrMembre();
                return View(membreService.MembreParClub(id));

            }
            
                
            
            else
            {
                return View(null);
            }
        }

        public ActionResult Create()
        {
            ClubService clubService = new ClubService();
           
            ViewData["Titre"] = "Creation de membre";

            ViewBag.IdClub = clubService.ListeClub();
            

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MembreVM model)
        {
            ClubController club=new ClubController();

            try
            {
                MembreService service = new MembreService();
                service.Ajouter(model);
                return RedirectToAction("list", "Club");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            MembreService membreService = new MembreService();
            
            ViewData["Titre"] = "Supression d'un membre";
           
            membreService.Supprimer(id);
            return RedirectToAction("list", "Club");
        }
        public ActionResult Edit(int id)
        {
            MembreService membreService = new MembreService();
            ClubService club=new ClubService();

            ViewBag.IdClub=club.ListeClub();
            ViewData["Titre"] = "Modifier un membre";


            MembreVM memb = membreService.Trouver(id);
            

            return View(memb);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MembreVM membre)
        {
            try
            {
                ClubService club = new ClubService();

                ViewBag.IdClub = club.ListeClub();
                MembreService service = new MembreService();
                service.Modifier(membre);
                return RedirectToAction("list", "Club");
            }
            catch
            {
                return View(nameof(Edit), membre);
            }
        }











    }
}

GestionClub/Views/Club/Create.cshtml
@model Models.Club.ClubVM

<h1>@ViewData["Titre"]</h1>

<form asp-controller="Club" asp-action="Create"
      method="post">
<div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">Nom :</label>
    <input asp-for="@Model.Nom" class="form-control" id="exampleFormControlInput1" >
</div>
<div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Description :</label>
    <input  asp-for="@Model.Description" class="form-control" id="exampleFormControlTextarea1" rows="3">
</div>
<div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">Date de Creation :</label>
    <input asp-for="@Model.DateCreation" type="date" class="form-control" id="exampleFormControlTextarea1" rows="3">
</div>
    <input type="submit" />
</form>

GestionClub/Views/Club/Edit.cshtml
@model Models.Club.ClubVM

<h1>@ViewData["Titre"]</h1>

<form asp-controller="Club" asp-action="Edit"
      method="post">
    <div class="mb-3">
        <label for="exampleFormControlInput1" class="form-label">Nom :</label>
        <input asp-for="@Model.Nom" class="form-control" id="exampleFormControlInput1">
    </div>
    <div class="mb-3">
        <label for="exampleFormControlTextarea1" class="form-label">Description :</label>
        <input asp-for="@Model.Description" class="form-control" id="exampleFormControlTextarea1" rows="3">
    </div>
    
    <input type="submit" />
</form>

GestionClub/Views/Club/Index.cshtml
<div class="container text-center">
    
    <h1 class="display-4">EMSI CLUB</h1>

    <div class="d-flex flex-wrap mx-auto">
        <img src="~/img/club1.png" style="width:200px;" class="m-2">
        <img src="~/img/club2.jpeg" style="width:200px;" class="m-2">
        <img src="~/img/club3.jpeg" style="width:200px;" class="m-2">
        <img src="~/img/club4.jpg" style="width:200px;" class="m-2">
        <img src="~/img/club 6.jpeg" style="width:200px;" class="m-2">
    </div>

    <div class="mt-3">
        
       
        <a href="@Url.Action("list", "Club")" class="btn btn-success">Liste des club</a>
    </div>
</div>

GestionClub/Views/Club/list.cshtml
@model List<Models.Club.ClubVM>

<h2>Liste des Clubs</h2>
<h4>
    Nombre de clubs : @ViewBag.nombreClub</h4>

<a asp-controller="Club" asp-action="Create" class="btn btn-primary btn-sm">Ajouter un club</a>
<a asp-controller="Membre" asp-action="Create"  class="btn btn-primary btn-sm">Ajouter un membre</a>
<a asp-controller="Activite" asp-action="Create" class="btn btn-primary btn-sm">Ajouter une activité</a>


<div class="row mt-3">
    <div class="col-md-12">

        <table class="table">
            <thead>
                <tr>

                    <th>nom</th>
                    <th>Descriprtion</th>
                    <th>Date de creation</th>



                </tr>
            </thead>

            <tbody>
                @foreach (var club in Model)
                {

                    <tr>

                        <td>@club.Nom</td>
                        <td>@club.Description</td>
                        <td>@club.DateCreation.ToString("dd/MM/yyyy")</td>

                        <td>

                            <a asp-controller="Club" asp-action="Edit" asp-route-id="@club.Id" class="btn btn-success btn-sm">Editer</a>
                            <a asp-controller="Club" asp-action="Delete" asp-route-id="@club.Id" class="btn btn-danger btn-sm">Supprimer</a>
                            <a asp-controller="Membre" asp-action="list" asp-route-id="@club.Id" class="btn btn-dark btn-sm">Membres</a>
                            <a asp-controller="Activite" asp-action="list" asp-route-id="@club.Id" class="btn btn-primary btn-sm">Activités</a>
                        </td>


                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>